Use GACB002D
GO
-----------------------------------------------------------------------TABELA CONCESSIONARIA - BLOCO 1
-- DROP TABLE dbo.GACE381D
CREATE TABLE dbo.GACE381D
(
	CODIGO_CONCESSIONARIA INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	NOME_CONCESSIONARIA VARCHAR(255)
)
GO

Insert into dbo.GACE381D values ('FIAT')
GO

--TABELA CONTRATO
-- DROP TABLE dbo.GACE382D
CREATE TABLE dbo.GACE382D
(
	ID INT IDENTITY(1,1) NOT NULL,
	CODIGO_CONTRATO VARCHAR(50) NOT NULL,
	TIPO_PESSOA CHAR(1) NOT NULL,
	DATA_INICIO_VIGENCIA DATETIME,
	DATA_FIM_VIGENCIA DATETIME,
	CODIGO_FIPE VARCHAR(25), 
	ANO_MODELO VARCHAR(4),
	PLACA VARCHAR(25),
	CHASSI VARCHAR(255),
	CEP_LOCAL_RISCO VARCHAR(10),
	TIPO_MOVIMENTO VARCHAR(50),
	CODIGO_CONCESSIONARIA INT FOREIGN KEY REFERENCES dbo.GACE381D(CODIGO_CONCESSIONARIA)
)
GO
-- DROP VIEW dbo.CONCESSIONARIA_MOTOR_FLEET
-- DROP VIEW dbo.CONTRATO_MOTOR_FLEET
---------------------------------------------------------------------------CRIAR VIEW COM IF NO LOCK - BLOCO 2
CREATE VIEW dbo.CONCESSIONARIA_MOTOR_FLEET AS SELECT * FROM dbo.GACE381D with (nolock)
GO
CREATE VIEW dbo.CONTRATO_MOTOR_FLEET AS SELECT * FROM dbo.GACE382D with (nolock)
GO

----------------------------------------------------------------------------PROCEDURE - BLOCO 3
--Checa se o id concessionária Existe
-- DROP PROCEDURE dbo.SP_VERIFICA_CONC_MOT_FLEET
CREATE PROCEDURE dbo.SP_VERIFICA_CONC_MOT_FLEET @Codigo Int
AS 
	Select Case When Exists ( Select codigo_concessionaria from dbo.CONCESSIONARIA_MOTOR_FLEET where CODIGO_CONCESSIONARIA = @Codigo ) 
				then CAST(1 as bit)
				else Cast(0 as bit)
			End
GO
--Criar Contrato
-- DROP PROCEDURE DBO.SP_INCLUI_CONTRATO_MOTOR_FLEET
CREATE PROCEDURE DBO.SP_INCLUI_CONTRATO_MOTOR_FLEET
(
	@CODIGO_CONTRATO VARCHAR(50),
	@TIPO_PESSOA CHAR(1),
	@DATA_INICIO_VIGENCIA DATETIME,
	@DATA_FIM_VIGENCIA DATETIME,
	@CODIGO_FIPE VARCHAR(25), 
	@ANO_MODELO VARCHAR(4),
	@PLACA VARCHAR(25),
	@CHASSI VARCHAR(255),
	@CEP_LOCAL_RISCO VARCHAR(10),
	@TIPO_MOVIMENTO VARCHAR(50),
	@CODIGO_CONCESSIONARIA INT

)
AS
	INSERT INTO dbo.CONTRATO_MOTOR_FLEET (
	CODIGO_CONTRATO, TIPO_PESSOA, DATA_INICIO_VIGENCIA,
	DATA_FIM_VIGENCIA, CODIGO_FIPE, ANO_MODELO, PLACA,
	CHASSI, CEP_LOCAL_RISCO, TIPO_MOVIMENTO, CODIGO_CONCESSIONARIA
	)
	VALUES (
	@CODIGO_CONTRATO, @TIPO_PESSOA, @DATA_INICIO_VIGENCIA,
	@DATA_FIM_VIGENCIA, @CODIGO_FIPE, @ANO_MODELO, @PLACA,
	@CHASSI, @CEP_LOCAL_RISCO, @TIPO_MOVIMENTO, @CODIGO_CONCESSIONARIA
	)
GO

-- DROP PROCEDURE DBO.SP_SELECT_CONTRATO_MOTOR_FLEET
--SELECIONA ContratoS
CREATE PROCEDURE DBO.SP_SELECT_CONTRATO_MOTOR_FLEET
(
	@CODIGO_CONTRATO VARCHAR(50)
)
AS
	SELECT 
	CODIGO_CONTRATO AS ContractNumber, CODIGO_CONCESSIONARIA AS DealershipCode, TIPO_PESSOA AS PersonType, DATA_INICIO_VIGENCIA AS StartDateEffective,
	DATA_FIM_VIGENCIA AS EndDateEffective, CODIGO_FIPE AS FIPECode, ANO_MODELO AS YearModelCar, PLACA AS PlateCar,
	CHASSI AS Chassi, CEP_LOCAL_RISCO AS RiskPlaceCEP, TIPO_MOVIMENTO AS MovementType
	FROM CONTRATO_MOTOR_FLEET
	WHERE CODIGO_CONTRATO = CASE WHEN @CODIGO_CONTRATO <> '' THEN @CODIGO_CONTRATO ELSE CODIGO_CONTRATO END   
GO

-- DROP PROCEDURE DBO.SP_SELECT_CONCESSIONARIA_MOTOR_FLEET
--SELECIONA Concessionaria
CREATE PROCEDURE DBO.SP_SELECT_CONCESSIONARIA_MOTOR_FLEET
(
	@CODIGO_CONCESSIONARIA INT
)
AS
	SELECT 
	CODIGO_CONTRATO AS ContractNumber, CODIGO_CONCESSIONARIA AS DealershipCode, TIPO_PESSOA AS PersonType, DATA_INICIO_VIGENCIA AS StartDateEffective,
	DATA_FIM_VIGENCIA AS EndDateEffective, CODIGO_FIPE AS FIPECode, ANO_MODELO AS YearModelCar, PLACA AS PlateCar,
	CHASSI AS Chassi, CEP_LOCAL_RISCO AS RiskPlaceCEP, TIPO_MOVIMENTO AS MovementType
	FROM CONTRATO_MOTOR_FLEET
	WHERE CODIGO_CONCESSIONARIA = CASE WHEN @CODIGO_CONCESSIONARIA <> 0 THEN @CODIGO_CONCESSIONARIA ELSE CODIGO_CONCESSIONARIA END 
GO

-----------------------------------------------------------------------------------------